version: '2'

services:
  app:
    build:
      context: ./docker/app
    environment:
      - PHP_IDE_CONFIG=serverName=trainjunkies_packages_darwin_webservice
    working_dir: /app
    env_file: .env
    volumes:
        - .:/app